apiVersion: v1
kind: Pod
metadata:
  name: bullseye
  namespace: default
spec:
  containers:
  - name: bullseye
    image: bullseye:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
